name: Semantic Release
description: 'Read outputs for matrix'
inputs:
  dry-run:
    description: 'Dry Run'
    required: true
  unset-gha-env:
    description: 'Unset GHA Env'
    required: false
  ci:
    description: 'CI'
    required: false

outputs:
  new_release_published:
    description: 'Whether a new release was published'
    value: ${{ steps.semantic_release.outputs.new_release_published }}
  new_release_version:
    description: 'Version of the new release'
    value: ${{ steps.semantic_release.outputs.new_release_version }}
  new_release_major_version:
    description: 'Major version of the new release'
    value: ${{ steps.semantic_release.outputs.new_release_major_version }}
  new_release_minor_version:
    description: 'Minor version of the new release'
    value: ${{ steps.semantic_release.outputs.new_release_minor_version }}
  new_release_patch_version:
    description: 'Patch version of the new release'
    value: ${{ steps.semantic_release.outputs.new_release_patch_version }}
  new_release_channel:
    description: 'The distribution channel on which the last release was initially made available (undefined for the default distribution channel).'
    value: ${{ steps.semantic_release.outputs.new_release_channel }}
  new_release_notes:
    description: 'The release notes for the new release.'
    value: ${{ steps.semantic_release.outputs.new_release_notes }}
  new_release_git_head:
    description: 'The sha of the last commit being part of the new release.'
    value: ${{ steps.semantic_release.outputs.new_release_git_head }}
  new_release_git_tag:
    description: 'The Git tag associated with the new release.'
    value: ${{ steps.semantic_release.outputs.new_release_git_tag }}
  last_release_version:
    description: 'Version of the previous release, if there was one.'
    value: ${{ steps.semantic_release.outputs.last_release_version }}
  last_release_git_head:
    description: 'The sha of the last commit being part of the last release, if there was one.'
    value: ${{ steps.semantic_release.outputs.last_release_git_head }}
  last_release_git_tag:
    description: 'The Git tag associated with the last release, if there was one.'
    value: ${{ steps.semantic_release.outputs.last_release_git_tag }}

runs:
  using: "composite"
  steps:
  - name: Semantic Release
    uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
    id: semantic_release
    with:
      semantic_version: 25.0.2
      dry_run: ${{ inputs.dry-run }}
      unset_gha_env: ${{ inputs.unset-gha-env || false }}
      ci: ${{ inputs.ci || true }}
      extra_plugins: |
        conventional-changelog-conventionalcommits
